import Head from "next/head";
import { AboutPage } from "@components/components/sub-pages/about";
import { SkillsPage } from "@components/components/sub-pages/skills";
import { HeroPage } from "@components/components/sub-pages/hero";
import { StyledMain } from "@components/components/main";
import { ProjectsPage } from "@components/components/sub-pages/projects";
import { WorkExperience } from "@components/components/sub-pages/work-experience";
import { Socials } from "@components/components/socials";
import { Header } from "@components/components/header";
import { Footer } from "@components/components/footer";
import { Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jacob Brown</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Jacob_Logo_32_32.png" />
      </Head>
      <Socials display={{ base: "none", md: "block" }} />
      <Box
        bg={"background"}
        _dark={{
          bg: "backgroundDark",
        }}
      >
        <Header />
        <StyledMain px={{ base: "2rem", md: "6rem" }}>
          <HeroPage />
          <AboutPage />
          <SkillsPage />
          <ProjectsPage />
          <WorkExperience />
        </StyledMain>
        <Footer />
      </Box>
    </>
  );
}
